# Generated by Django 4.1.7 on 2023-02-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscribed_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_packs',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
