# Generated by Django 4.1.7 on 2023-02-17 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_subscription_packs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_users',
            name='subscription_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.subscription_packs'),
        ),
    ]
