# Generated by Django 4.1.7 on 2023-02-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_subscribed_users_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
