# Generated by Django 4.1.7 on 2023-04-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_consultant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='not-specfied', max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='employment_status',
            field=models.CharField(default='not-specfied', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='employment_type',
            field=models.CharField(default='not-specfied', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='job_type',
            field=models.CharField(default='not-specfied', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(default='not-specfied', max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='not-specfied', max_length=50),
        ),
    ]
